spring:
  profiles:
    active: @spring.profiles.active@
jwt:
  secret: SecretKeyToGenJWTszerbghbegilrzlbgzerlelrzbgqlgrbgzlhjkghjklzbzrglfbzeREZGERGfbZALIBHZEliblBHBDLIABNJEBELZFBFLZEbefzlkbzeflLZ
  expires_in: 86400
  cookie: AUTH-TOKEN
