spring:
  datasource:
    url: jdbc:mysql://bitgmvbedipqkkt0vf1q-mysql.services.clever-cloud.com:21394/bitgmvbedipqkkt0vf1q
    username: u50yotuu1hihajwo
    password: lgfAdcxNwvOkkQZMR4d
  jpa:
    generate-ddl: true
    show-sql: true
logging:
  level:
    org:
      springframework:
        security: DEBUG
